edition = "2021"
force_explicit_abi = true
fn_args_layout = "Tall"
hard_tabs = false
imports_granularity = "One"
max_width = 120
merge_derives = true
newline_style = "Auto"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
